import { db, categoriesTable, subscriptionServicesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Seeding database...");

  await db.execute(sql`TRUNCATE TABLE user_subscriptions, subscription_services, categories RESTART IDENTITY CASCADE`);

  const [streaming, productivity, gaming, health, education, news, security, music] = await db
    .insert(categoriesTable)
    .values([
      { name: "Streaming", slug: "streaming", icon: "📺", description: "Video and TV streaming services", serviceCount: 0 },
      { name: "Productivity", slug: "productivity", icon: "⚡", description: "Tools to boost your workflow", serviceCount: 0 },
      { name: "Gaming", slug: "gaming", icon: "🎮", description: "Gaming platforms and services", serviceCount: 0 },
      { name: "Health & Fitness", slug: "health", icon: "💪", description: "Health, fitness and wellness apps", serviceCount: 0 },
      { name: "Education", slug: "education", icon: "📚", description: "Online learning platforms", serviceCount: 0 },
      { name: "News & Media", slug: "news", icon: "📰", description: "News and media subscriptions", serviceCount: 0 },
      { name: "Security", slug: "security", icon: "🔒", description: "VPN, password managers and security tools", serviceCount: 0 },
      { name: "Music", slug: "music", icon: "🎵", description: "Music streaming and audio services", serviceCount: 0 },
    ])
    .returning();

  await db.insert(subscriptionServicesTable).values([
    {
      name: "StreamFlix",
      description: "The ultimate streaming platform with thousands of movies, TV shows, and original content. Watch anywhere, anytime.",
      logo: "🎬",
      categoryId: streaming.id,
      priceMonthly: "15.99",
      priceAnnual: "149.99",
      currency: "USD",
      rating: "4.8",
      reviewCount: 128420,
      subscriberCount: 85420,
      features: ["4K Ultra HD", "Download offline", "4 screens simultaneously", "100+ originals", "No ads"],
      tags: ["movies", "tv shows", "originals", "4k"],
      isFeatured: true,
      website: "https://streamflix.example.com",
    },
    {
      name: "CineVault",
      description: "Classic and indie films curated for the discerning viewer. Discover hidden gems and cult classics.",
      logo: "🎞️",
      categoryId: streaming.id,
      priceMonthly: "9.99",
      priceAnnual: "89.99",
      currency: "USD",
      rating: "4.5",
      reviewCount: 34280,
      subscriberCount: 22100,
      features: ["HD Streaming", "Curated collections", "Director spotlights", "Film festivals", "Mobile app"],
      tags: ["classic films", "indie", "art house", "documentary"],
      isFeatured: false,
      website: "https://cinevault.example.com",
    },
    {
      name: "ProSuite",
      description: "All-in-one productivity suite with documents, spreadsheets, project management, and team collaboration tools.",
      logo: "💼",
      categoryId: productivity.id,
      priceMonthly: "12.99",
      priceAnnual: "119.99",
      currency: "USD",
      rating: "4.7",
      reviewCount: 89320,
      subscriberCount: 65800,
      features: ["Unlimited storage", "Real-time collaboration", "AI writing assistant", "Custom workflows", "API access"],
      tags: ["documents", "spreadsheets", "collaboration", "AI"],
      isFeatured: true,
      website: "https://prosuite.example.com",
    },
    {
      name: "TaskFlow",
      description: "Smart project management and task tracking for individuals and teams. Stay organized and hit your deadlines.",
      logo: "✅",
      categoryId: productivity.id,
      priceMonthly: "8.99",
      priceAnnual: "79.99",
      currency: "USD",
      rating: "4.6",
      reviewCount: 45120,
      subscriberCount: 38900,
      features: ["Unlimited projects", "Kanban & Gantt views", "Time tracking", "Integrations", "Mobile apps"],
      tags: ["tasks", "projects", "kanban", "team"],
      isFeatured: false,
      website: null,
    },
    {
      name: "GamePass Pro",
      description: "Access hundreds of premium games on PC, console, and cloud. New games added every month.",
      logo: "🕹️",
      categoryId: gaming.id,
      priceMonthly: "14.99",
      priceAnnual: "134.99",
      currency: "USD",
      rating: "4.9",
      reviewCount: 234100,
      subscriberCount: 192400,
      features: ["300+ games", "Day-one releases", "Cloud gaming", "Exclusive discounts", "Multiplayer included"],
      tags: ["games", "cloud gaming", "console", "PC"],
      isFeatured: true,
      website: "https://gamepasspro.example.com",
    },
    {
      name: "FitTrack",
      description: "Personalized fitness plans, nutrition tracking, and live classes. Achieve your health goals with expert guidance.",
      logo: "🏋️",
      categoryId: health.id,
      priceMonthly: "19.99",
      priceAnnual: "179.99",
      currency: "USD",
      rating: "4.7",
      reviewCount: 67800,
      subscriberCount: 54200,
      features: ["1000+ workouts", "Live classes", "AI meal planner", "Progress tracking", "Personal coach"],
      tags: ["fitness", "workout", "nutrition", "wellness"],
      isFeatured: false,
      website: null,
    },
    {
      name: "MindfulMe",
      description: "Guided meditation, sleep sounds, and mindfulness exercises. Reduce stress and improve mental wellbeing.",
      logo: "🧘",
      categoryId: health.id,
      priceMonthly: "12.99",
      priceAnnual: "99.99",
      currency: "USD",
      rating: "4.8",
      reviewCount: 43200,
      subscriberCount: 38700,
      features: ["500+ meditations", "Sleep stories", "Breathing exercises", "Daily check-ins", "Offline access"],
      tags: ["meditation", "mindfulness", "sleep", "stress"],
      isFeatured: true,
      website: "https://mindfulme.example.com",
    },
    {
      name: "LearnPath",
      description: "Expert-led courses in tech, business, design, and more. Learn at your own pace with certificates upon completion.",
      logo: "🎓",
      categoryId: education.id,
      priceMonthly: "29.99",
      priceAnnual: "249.99",
      currency: "USD",
      rating: "4.6",
      reviewCount: 98400,
      subscriberCount: 72100,
      features: ["10,000+ courses", "Certificates", "Offline access", "Expert instructors", "Learning paths"],
      tags: ["courses", "learning", "certificates", "skills"],
      isFeatured: false,
      website: "https://learnpath.example.com",
    },
    {
      name: "CodeMaster",
      description: "Interactive coding courses for all skill levels. From beginner to advanced, master programming languages and frameworks.",
      logo: "👨‍💻",
      categoryId: education.id,
      priceMonthly: "24.99",
      priceAnnual: "199.99",
      currency: "USD",
      rating: "4.9",
      reviewCount: 76500,
      subscriberCount: 61300,
      features: ["Live coding environment", "Project-based learning", "Mentorship", "Job placement help", "100+ languages"],
      tags: ["coding", "programming", "developer", "bootcamp"],
      isFeatured: true,
      website: null,
    },
    {
      name: "NewsHub+",
      description: "Curated news from hundreds of trusted sources. Stay informed with personalized feeds and in-depth analysis.",
      logo: "📡",
      categoryId: news.id,
      priceMonthly: "6.99",
      priceAnnual: "59.99",
      currency: "USD",
      rating: "4.4",
      reviewCount: 28900,
      subscriberCount: 24600,
      features: ["500+ publications", "Ad-free reading", "Audio articles", "Newsletter archive", "Daily digest"],
      tags: ["news", "media", "journalism", "current events"],
      isFeatured: false,
      website: "https://newshub.example.com",
    },
    {
      name: "SecureVPN",
      description: "Military-grade VPN with global servers for complete online privacy and security. Protect all your devices.",
      logo: "🛡️",
      categoryId: security.id,
      priceMonthly: "9.99",
      priceAnnual: "79.99",
      currency: "USD",
      rating: "4.7",
      reviewCount: 54300,
      subscriberCount: 47800,
      features: ["5000+ servers", "No logs policy", "Kill switch", "Split tunneling", "10 devices"],
      tags: ["vpn", "privacy", "security", "anonymous"],
      isFeatured: false,
      website: "https://securevpn.example.com",
    },
    {
      name: "KeyVault",
      description: "Secure password manager and digital identity protection. Generate, store, and autofill passwords across all devices.",
      logo: "🔑",
      categoryId: security.id,
      priceMonthly: "3.99",
      priceAnnual: "29.99",
      currency: "USD",
      rating: "4.8",
      reviewCount: 87200,
      subscriberCount: 78400,
      features: ["Unlimited passwords", "Secure sharing", "Dark web monitoring", "2FA support", "Emergency access"],
      tags: ["passwords", "security", "identity", "2fa"],
      isFeatured: true,
      website: null,
    },
    {
      name: "BeatStream",
      description: "Stream over 100 million songs with lossless audio quality. Discover new music with AI-powered recommendations.",
      logo: "🎶",
      categoryId: music.id,
      priceMonthly: "9.99",
      priceAnnual: "89.99",
      currency: "USD",
      rating: "4.8",
      reviewCount: 198400,
      subscriberCount: 165200,
      features: ["100M+ songs", "Lossless audio", "Offline playlists", "Podcast library", "Family plan"],
      tags: ["music", "streaming", "podcasts", "lossless"],
      isFeatured: true,
      website: "https://beatstream.example.com",
    },
    {
      name: "PodcastPro",
      description: "The ultimate podcast platform with exclusive shows, live recordings, and creator tools for aspiring podcasters.",
      logo: "🎙️",
      categoryId: music.id,
      priceMonthly: "7.99",
      priceAnnual: "69.99",
      currency: "USD",
      rating: "4.5",
      reviewCount: 32100,
      subscriberCount: 27900,
      features: ["Exclusive shows", "Ad-free listening", "Offline downloads", "Creator tools", "Video podcasts"],
      tags: ["podcasts", "audio", "creator", "exclusive"],
      isFeatured: false,
      website: null,
    },
  ]);

  const serviceCounts = await db.execute(
    sql`SELECT category_id, COUNT(*) as cnt FROM subscription_services GROUP BY category_id`
  );

  for (const row of serviceCounts.rows as { category_id: number; cnt: string }[]) {
    await db.execute(
      sql`UPDATE categories SET service_count = ${Number(row.cnt)} WHERE id = ${row.category_id}`
    );
  }

  console.log("Database seeded successfully!");
}

seed().catch(console.error).finally(() => process.exit(0));
